export const sampleFeedbackData = [
	{
		category: "UI",
		sentiment: "positive",
		comment: "UIがとても使いやすい！",
		rating: 5,
	},
	{
		category: "FeatureRequest",
		sentiment: "neutral",
		comment: "新しい通知機能が欲しいです。",
		rating: 3,
	},
	{
		category: "Pricing",
		sentiment: "negative",
		comment: "価格が高く感じます。もう少し安くならないですか？",
		rating: 2,
	},
	{
		category: "UI",
		sentiment: "negative",
		comment: "スマホ表示のレイアウトが崩れています。",
		rating: 1,
	},
	{
		category: "Support",
		sentiment: "positive",
		comment: "問い合わせ対応が早くて助かりました。",
		rating: 4,
	},
	{
		category: "UI",
		sentiment: "positive",
		comment: "ダークモードが綺麗！",
		rating: 5,
	},
	{
		category: "UI",
		sentiment: "positive",
		comment: "新しいデザインが素晴らしいです。",
		rating: 5,
	},
	{
		category: "FeatureRequest",
		sentiment: "neutral",
		comment: "音声入力にも対応してほしいです。",
		rating: 3,
	},
	{
		category: "Pricing",
		sentiment: "negative",
		comment: "プレミアムプランが高すぎます。",
		rating: 2,
	},
	{
		category: "Support",
		sentiment: "positive",
		comment: "チャットサポートの対応が早くて助かった。",
		rating: 4,
	},
	{
		category: "Performance",
		sentiment: "negative",
		comment: "起動が遅くて使いづらいです。",
		rating: 2,
	},
	{
		category: "Accessibility",
		sentiment: "neutral",
		comment: "音声読み上げ機能の改善を希望します。",
		rating: 3,
	},
	{
		category: "FeatureRequest",
		sentiment: "positive",
		comment: "オフラインでも使えるようにしてほしい。",
		rating: 4,
	},
	{
		category: "Support",
		sentiment: "negative",
		comment: "返信が遅かったのが残念です。",
		rating: 2,
	},
	{
		category: "UI",
		sentiment: "positive",
		comment: "カスタムテーマ機能がとても便利です。",
		rating: 4,
	},
	{
		category: "FeatureRequest",
		sentiment: "neutral",
		comment: "プラグイン機能の拡張を検討してほしいですね。",
		rating: 3,
	},
	{
		category: "UI",
		sentiment: "positive",
		comment: "新しいレイアウトが直感的で素晴らしいです！",
		rating: 5,
	},
	{
		category: "UI",
		sentiment: "negative",
		comment: "ボタンがどこにあるかわかりづらいです。",
		rating: 2,
	},
	{
		category: "UI",
		sentiment: "neutral",
		comment: "デザインは良いですが、特に目立った点はありません。",
		rating: 3,
	},
	{
		category: "FeatureRequest",
		sentiment: "positive",
		comment: "新しいカスタマイズ機能が便利で助かっています。",
		rating: 4,
	},
	{
		category: "FeatureRequest",
		sentiment: "negative",
		comment: "重要な機能がまだ不足していると感じます。",
		rating: 2,
	},
	{
		category: "FeatureRequest",
		sentiment: "neutral",
		comment: "機能追加は良いですが、頻度がもっと多いと嬉しいです。",
		rating: 3,
	},
	{
		category: "Pricing",
		sentiment: "positive",
		comment: "他社と比べてコストパフォーマンスが非常に良いです！",
		rating: 5,
	},
	{
		category: "Pricing",
		sentiment: "negative",
		comment: "コスパが悪いと感じます。もっと安いプランが欲しいです。",
		rating: 1,
	},
	{
		category: "Pricing",
		sentiment: "neutral",
		comment: "価格は妥当ですが、もう少し割引があると良いと思います。",
		rating: 3,
	},
	{
		category: "Support",
		sentiment: "positive",
		comment: "サポートが丁寧で素早い対応に感謝しています。",
		rating: 5,
	},
	{
		category: "Support",
		sentiment: "negative",
		comment: "サポートに連絡しても返信が遅く、不満です。",
		rating: 2,
	},
	{
		category: "Support",
		sentiment: "neutral",
		comment: "サポートの対応は普通でした。特に不満もありません。",
		rating: 3,
	},
	{
		category: "Performance",
		sentiment: "positive",
		comment: "操作がとてもスムーズで快適です！",
		rating: 5,
	},
	{
		category: "Performance",
		sentiment: "negative",
		comment: "動作が遅く、たびたびフリーズします。",
		rating: 1,
	},
	{
		category: "Performance",
		sentiment: "neutral",
		comment: "動作は悪くありませんが、改善の余地があります。",
		rating: 3,
	},
	{
		category: "Accessibility",
		sentiment: "positive",
		comment: "視覚支援機能が充実していて、非常に助かります。",
		rating: 4,
	},
	{
		category: "Accessibility",
		sentiment: "negative",
		comment: "障がい者向けの機能が十分でないと感じます。",
		rating: 2,
	},
	{
		category: "Accessibility",
		sentiment: "neutral",
		comment: "基本的な支援機能はありますが、特に目立った改善はないです。",
		rating: 3,
	},
	{
		category: "UI",
		sentiment: "positive",
		comment: "テーマの変更が簡単で気に入っています。",
		rating: 4,
	},
	{
		category: "FeatureRequest",
		sentiment: "negative",
		comment: "要望を出してもなかなか反映されないのが残念です。",
		rating: 2,
	},
];
